import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#8f4a00",
        "primary-container": "#ae611a",
        "primary-fixed": "#ffdcc4",
        "primary-fixed-dim": "#ffb781",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#2f1400",
        "on-primary-fixed-variant": "#6f3800",
        secondary: "#835418",
        "secondary-container": "#fdbd77",
        "secondary-fixed": "#ffdcbb",
        "secondary-fixed-dim": "#faba75",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#784a0d",
        "on-secondary-fixed": "#2b1700",
        "on-secondary-fixed-variant": "#673d00",
        tertiary: "#55612e",
        "tertiary-container": "#6e7a44",
        "tertiary-fixed": "#dbe9a9",
        "tertiary-fixed-dim": "#bfcd8f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fcffe3",
        "on-tertiary-fixed": "#171e00",
        "on-tertiary-fixed-variant": "#404b1b",
        background: "#fefae0",
        "on-background": "#1d1c0d",
        surface: "#fefae0",
        "surface-dim": "#dedbc2",
        "surface-bright": "#fefae0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f4db",
        "surface-container": "#f2efd5",
        "surface-container-high": "#ede9cf",
        "surface-container-highest": "#e7e3ca",
        "surface-tint": "#924c00",
        "surface-variant": "#e7e3ca",
        "on-surface": "#1d1c0d",
        "on-surface-variant": "#544438",
        "inverse-surface": "#323120",
        "inverse-on-surface": "#f5f1d8",
        "inverse-primary": "#ffb781",
        outline: "#877366",
        "outline-variant": "#d9c2b3",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Newsreader", "Georgia", "serif"],
        body: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        sans: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ["Newsreader", "Georgia", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config;
