/** @type {import('tailwindcss').Config} */
export default {
  content: ["./app/**/{**,.client,.server}/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#eab464",
        "primary-container": "#ae611a",
        "primary-fixed": "#ffdcc4",
        "primary-fixed-dim": "#ffb781",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#2f1400",
        "on-primary-fixed-variant": "#6f3800",
        secondary: "#835418",
        "secondary-container": "#fdbd77",
        "secondary-fixed": "#ffdcbb",
        "secondary-fixed-dim": "#faba75",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#784a0d",
        "on-secondary-fixed": "#2b1700",
        "on-secondary-fixed-variant": "#673d00",
        tertiary: "#eab464",
        "tertiary-container": "#6e7a44",
        "tertiary-fixed": "#dbe9a9",
        "tertiary-fixed-dim": "#bfcd8f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fcffe3",
        "on-tertiary-fixed": "#171e00",
        "on-tertiary-fixed-variant": "#404b1b",
        background: "#0c1611",
        "on-background": "#edf0e4",
        surface: "#10211a",
        "surface-dim": "#dedbc2",
        "surface-bright": "#fefae0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#13241b",
        "surface-container": "#1b2c22",
        "surface-container-high": "#223428",
        "surface-container-highest": "#e7e3ca",
        "surface-tint": "#924c00",
        "surface-variant": "#e7e3ca",
        "on-surface": "#edf0e4",
        "on-surface-variant": "#a7b6a9",
        "inverse-surface": "#323120",
        "inverse-on-surface": "#f5f1d8",
        "inverse-primary": "#ffb781",
        outline: "#7c8d80",
        "outline-variant": "#d9c2b3",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        foreground: "var(--foreground)",
        border: "var(--border)",
        ring: "var(--ring)",
        input: "var(--input)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        destructive: "var(--destructive)",
        "primary-foreground": "var(--primary-foreground)",
        "secondary-foreground": "var(--secondary-foreground)",
      },
      fontFamily: {
        headline: ["Newsreader", "Georgia", "serif"],
        body: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        sans: ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ["Newsreader", "Georgia", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
